source 'https://cdn.cocoapods.org'

use_frameworks!


target 'WZFoundationExtension_Example' do
  pod 'WZFoundationExtension', :path => '../'
#  pod 'WZSnapKit', '~> 3.1.3' #布局框架
  
  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['ENABLE_BITCODE'] = 'NO'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = 13.0
        if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
          target.build_configurations.each do |config|
              config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
          end
        end
      end
    end
  end
end
